version: '3.8'

services:
  backend:
    build: ./backend
    container_name: save2serve-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/Save2Serve
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: save2serve-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: save2serve-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=Save2Serve

volumes:
  mongo_data: